- name: List schemes
  run: xcodebuild -list -project Protokolle.xcodeproj

- name: Build
  run: |
    xcodebuild \
    -project Protokolle.xcodeproj \
    -scheme Protokolle \
    -sdk iphoneos \
    -configuration Release \
    -derivedDataPath build \
    CODE_SIGNING_ALLOWED=NO
